"""Structural boundaries implemented by infrastructure adapters."""
from typing import Protocol


class CatalogPort(Protocol):
    def register(self, name: str, repositories: list[str], idempotency_key: str) -> dict: ...
    def list_projects(self) -> list[dict]: ...
    def get_project(self, project_id: str) -> dict: ...
